name: Test Embedded

on:
  push:
    branches: ["develop", "deploy"]
  pull_request:
    branches: ["develop", "deploy"]
  release:
    types: [published]


jobs:
  build-embedded:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: 3.11.0

    steps:

    - name: Set up Python (regular distribution)
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }} # Use the same version as the embeddable version
    
    - name: Setup python embeddable version
      run: |
        # Create a directory for the embeddable Python version
        mkdir python-${{ env.PYTHON_VERSION }}
        
        # Download and unzip the embeddable Python version
        curl -O https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/python-${{ env.PYTHON_VERSION }}-embed-amd64.zip
        unzip python-${{ env.PYTHON_VERSION }}-embed-amd64.zip -d python-${{ env.PYTHON_VERSION }}
        rm python-${{ env.PYTHON_VERSION }}-embed-amd64.zip
        
        # Define paths for the regular Python distribution and the embeddable distribution
        ls -la ${{ runner.tool_cache }}/Python/${{ env.PYTHON_VERSION }}
        PYTHON_DIR="${{ runner.tool_cache }}/Python/${{ env.PYTHON_VERSION }}/x64" # Path from actions/setup-python
        EMBED_DIR="python-${{ env.PYTHON_VERSION }}"
        
        # Copy necessary Tkinter files from the regular Python distribution
        cp -r $PYTHON_DIR/tcl $EMBED_DIR/
        cp -r $PYTHON_DIR/Lib/tkinter $EMBED_DIR/Lib/
        cp $PYTHON_DIR/DLLs/_tkinter.pyd $EMBED_DIR/DLLs/
        cp $PYTHON_DIR/DLLs/tcl86t.dll $EMBED_DIR/DLLs/
        cp $PYTHON_DIR/DLLs/tk86t.dll $EMBED_DIR/DLLs/
